flowchart LR
  controller --> java2js
  jsconsole --> java2js
  jscontrols --> controller
  jscontrols --> java2js
  jseditor --> java2js
  jsmenu --> controller
  parser --> exp
  parser --> tokenscanner
  parser --> utf8
  programeditor --> jseditor
  programeditor --> java2js
  sjs --> parser
  sjs --> exp
  sjs --> jsmenu
  sjs --> svm
  sjs --> java2js
  sjs --> controller
  sjs --> jscontrols
  sjs --> graphics
  sjs --> jsconsole
  sjs --> file
  sjs --> sjslib
  sjs --> svmtools
  sjs --> shellargs
  sjs --> tokenscanner
  svm --> exp
  svm --> parser
  svm --> tokenscanner
  svm --> java2js
  svm --> jsconsole
  svm --> controller
  svm --> utf8
  svmtools --> programeditor
  svmtools --> tokenscanner